package com.qext2.primary.model

data class StatsRideSnapshot(
    val npWholeWatts: Int = 0,
    val ifWholeRide: Float = 0f,
    val viValue: Float = 0f,
    val tssValue: Float = 0f,
    val caloriesKcal: Int = 0,
    val carbsGPerH: Int = 0,
    val carbBalanceG: Int = 0,
    val fluidLPerH: Float = 0f,
    val rideReservePercent: Int = 100,
    val wBalancePercent: Int = -1,
    val wBalanceTrend: String = "stable",
    val etaTimestamp: Long = 0L,
    val ascentDoneM: Int = 0,
    val ascentLeftM: Int = 0,
    val hasRoute: Boolean = false,
    val routeClimbSourceReady: Boolean = false,
    val batterySourceReady: Boolean = false,
    val batteryDrainReady: Boolean = false,
    val batteryEstimateReady: Boolean = false,
    val wPrimeModelReady: Boolean = false,
    val etaModelReady: Boolean = false,
    val rsrvModelReady: Boolean = false,
    val carbModelReady: Boolean = false,
    val fluidModelReady: Boolean = false,
    val weatherFresh: Boolean = false,
    val weatherTemperatureC: Float? = null,
    val weatherWindSpeedMps: Float? = null,
    val weatherRain1hMm: Float? = null,
    val weatherCondition: String? = null,
    val batterySource: String? = null,
    val batteryDrainPctPerHour: Float? = null,
    val batteryTimeLeftSec: Long? = null,
    val grossElapsedSec: Long = 0L,
    val distanceKm: Float = 0f,
)
